### ISSUE TITLE
[Types] Improve the IMessage type

### ISSUE THREAD

**Issue by Slawaq** [ZitRos/node-message-bus#1]
Hi @ZitRos, 
I believe you can use a generic type for this field:
https://github.com/ZitRos/node-message-bus/blob/8e6af0b274abaf4405a4ab0567a373bb4b2ed542/src/Types/message.ts#L3

Like:
```ts
export interface IMessage<TKey extends string, TData = unknown> {
  routingKey: TKey;
  data: TData;
}
```
And regarding this change the example from the readme:
```ts
type MessageWorkerTaskA = IMessage<
  'worker.task-a',
  {
    typed: string
  }
>

type MessageWorkerTaskB = IMessage<'worker.task-b', number>
```

**Comment by nikitaeverywhere** [comment]
Thanks for suggesting `unknown`, indeed a better match.

**Comment by nikitaeverywhere** [comment]
@slawaq, so this:

```typescript
export interface IMessage<
  TRoutingKey extends string = string,
  TData = unknown
> {
  routingKey: TRoutingKey;
  data: TData;
}
```

However, my original idea was to **enforce** people to provide both `routingKey` and `data` types, if they provide a type. Any idea how to better manage it?

<img width="441" alt="image" src="https://user-images.githubusercontent.com/4989256/162726954-7d2cca93-5768-4ff4-acab-48a3c098753a.png">

If you remove `extends` (or generic), it validates it correctly:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/4989256/162727432-ab86730f-e14d-4176-b6c2-636b0f9f4f11.png">

**Comment by nikitaeverywhere** [comment]
I can see that if we leave it as generic, we can make it required (just by avoiding `=`). However generics are less readable.

I will keep declarations as you suggested.
